Arithmetic operation

In [1]:
import pandas as pd

In [2]:
var  = pd.DataFrame({"A":[1,2,3,4,5],"B":[9,8,7,6,5]})
print(var)

   A  B
0  1  9
1  2  8
2  3  7
3  4  6
4  5  5

In [4]:
var["c"] = var["A"] + var["B"]
var

   A  B   c
0  1  9  10
1  2  8  10
2  3  7  10
3  4  6  10
4  5  5  10

In [11]:
var["c"] = var["a"] - var["B"]
var

   a  B  c
0  1  9 -8
1  2  8 -6
2  3  7 -4
3  4  6 -2
4  5  5  0

In [12]:
var["c"] = var["a"] * var["B"]
var

   a  B   c
0  1  9   9
1  2  8  16
2  3  7  21
3  4  6  24
4  5  5  25

In [13]:
var["c"] = var["a"] / var["B"]
var

   a  B         c
0  1  9  0.111111
1  2  8  0.250000
2  3  7  0.428571
3  4  6  0.666667
4  5  5  1.000000

In [20]:
var1  = pd.DataFrame({"A":[10,20,30,40,50],"B":[15,80,70,60,50]})
var1

    A   B
0  10  15
1  20  80
2  30  70
3  40  60
4  50  50

In [21]:
var1["Greater"] = var1["A"] <=20
var1["LessThan"]= var1["B"] >=40
var1

    A   B  Greater  LessThan
0  10  15     True     False
1  20  80     True      True
2  30  70    False      True
3  40  60    False      True
4  50  50    False      True