Finding Missing Value Data

In [4]:
import numpy as np
import pandas as pd

In [5]:
data = pd.read_csv("Student2.csv")
df = pd.DataFrame(data)
df

,S No.,Student Name,Age,Hindi,English,Maths,Geography,History,Marks_Total,Maximum,Minimum,Count,AVG,%TAGE,Result,Grade,Result1
0,1,Paras,21.0,32.0,80,90.0,90.0,78,370.0,90,32.0,5.0,74.0,74.0,Fail,A,NaN
1,2,Mahendra,20.0,85.0,12,65.0,80.0,91,333.0,91,12.0,5.0,66.6,66.6,Fail,A,NaN
2,3,Simaran,NaN,91.0,65,23.0,NaN,45,294.0,91,23.0,NaN,58.8,58.8,Fail,B,NaN
3,4,Sonu,23.0,71.0,45,45.0,60.0,33,254.0,71,33.0,5.0,50.8,50.8,Pass,C,NaN
4,5,Dipak,19.0,NaN,32,85.0,50.0,48,NaN,85,32.0,5.0,60.0,60.0,NaN,B,NaN
5,6,Rana,18.0,73.0,30,39.0,40.0,7,189.0,73,7.0,5.0,37.8,37.8,Fail,D,NaN
6,7,Sonam,17.0,25.0,40,48.0,26.0,15,154.0,48,NaN,5.0,30.8,30.8,Fail,F,NaN
7,8,Shubham,20.0,81.0,78,76.0,56.0,65,356.0,81,56.0,5.0,71.2,71.2,Pass,A,NaN
8,9,Engla,24.0,88.0,32,1.0,48.0,35,204.0,88,1.0,5.0,40.8,40.8,Fail,C,NaN
9,10,Juhi,NaN,50.0,85,NaN,32.0,38,250.0,85,32.0,5.0,50.0,50.0,Fail,C,NaN

In [6]:
df.isnull().sum()

S No.             0
Student Name      0
Age               2
Hindi             1
English           0
Maths             1
Geography         1
History           0
Marks_Total       1
Maximum           0
Minimum           1
Count             1
AVG               0
%TAGE             0
Result            1
Grade             0
Result1          10
dtype: int64

In [7]:
df.isna().any()

S No.            False
Student Name     False
Age               True
Hindi             True
English          False
Maths             True
Geography         True
History          False
Marks_Total       True
Maximum          False
Minimum           True
Count             True
AVG              False
%TAGE            False
Result            True
Grade            False
Result1           True
dtype: bool

In [8]:
df.head(5)

,S No.,Student Name,Age,Hindi,English,Maths,Geography,History,Marks_Total,Maximum,Minimum,Count,AVG,%TAGE,Result,Grade,Result1
0,1,Paras,21.0,32.0,80,90.0,90.0,78,370.0,90,32.0,5.0,74.0,74.0,Fail,A,NaN
1,2,Mahendra,20.0,85.0,12,65.0,80.0,91,333.0,91,12.0,5.0,66.6,66.6,Fail,A,NaN
2,3,Simaran,NaN,91.0,65,23.0,NaN,45,294.0,91,23.0,NaN,58.8,58.8,Fail,B,NaN
3,4,Sonu,23.0,71.0,45,45.0,60.0,33,254.0,71,33.0,5.0,50.8,50.8,Pass,C,NaN
4,5,Dipak,19.0,NaN,32,85.0,50.0,48,NaN,85,32.0,5.0,60.0,60.0,NaN,B,NaN

In [9]:
df.dropna(thresh=5) #thresh is use for drop where mininum null in Rows

,S No.,Student Name,Age,Hindi,English,Maths,Geography,History,Marks_Total,Maximum,Minimum,Count,AVG,%TAGE,Result,Grade,Result1
0,1,Paras,21.0,32.0,80,90.0,90.0,78,370.0,90,32.0,5.0,74.0,74.0,Fail,A,NaN
1,2,Mahendra,20.0,85.0,12,65.0,80.0,91,333.0,91,12.0,5.0,66.6,66.6,Fail,A,NaN
2,3,Simaran,NaN,91.0,65,23.0,NaN,45,294.0,91,23.0,NaN,58.8,58.8,Fail,B,NaN
3,4,Sonu,23.0,71.0,45,45.0,60.0,33,254.0,71,33.0,5.0,50.8,50.8,Pass,C,NaN
4,5,Dipak,19.0,NaN,32,85.0,50.0,48,NaN,85,32.0,5.0,60.0,60.0,NaN,B,NaN
5,6,Rana,18.0,73.0,30,39.0,40.0,7,189.0,73,7.0,5.0,37.8,37.8,Fail,D,NaN
6,7,Sonam,17.0,25.0,40,48.0,26.0,15,154.0,48,NaN,5.0,30.8,30.8,Fail,F,NaN
7,8,Shubham,20.0,81.0,78,76.0,56.0,65,356.0,81,56.0,5.0,71.2,71.2,Pass,A,NaN
8,9,Engla,24.0,88.0,32,1.0,48.0,35,204.0,88,1.0,5.0,40.8,40.8,Fail,C,NaN
9,10,Juhi,NaN,50.0,85,NaN,32.0,38,250.0,85,32.0,5.0,50.0,50.0,Fail,C,NaN

In [11]:
df.fillna(0)

,S No.,Student Name,Age,Hindi,English,Maths,Geography,History,Marks_Total,Maximum,Minimum,Count,AVG,%TAGE,Result,Grade,Result1
0,1,Paras,21.0,32.0,80,90.0,90.0,78,370.0,90,32.0,5.0,74.0,74.0,Fail,A,0.0
1,2,Mahendra,20.0,85.0,12,65.0,80.0,91,333.0,91,12.0,5.0,66.6,66.6,Fail,A,0.0
2,3,Simaran,0.0,91.0,65,23.0,0.0,45,294.0,91,23.0,0.0,58.8,58.8,Fail,B,0.0
3,4,Sonu,23.0,71.0,45,45.0,60.0,33,254.0,71,33.0,5.0,50.8,50.8,Pass,C,0.0
4,5,Dipak,19.0,0.0,32,85.0,50.0,48,0.0,85,32.0,5.0,60.0,60.0,0,B,0.0
5,6,Rana,18.0,73.0,30,39.0,40.0,7,189.0,73,7.0,5.0,37.8,37.8,Fail,D,0.0
6,7,Sonam,17.0,25.0,40,48.0,26.0,15,154.0,48,0.0,5.0,30.8,30.8,Fail,F,0.0
7,8,Shubham,20.0,81.0,78,76.0,56.0,65,356.0,81,56.0,5.0,71.2,71.2,Pass,A,0.0
8,9,Engla,24.0,88.0,32,1.0,48.0,35,204.0,88,1.0,5.0,40.8,40.8,Fail,C,0.0
9,10,Juhi,0.0,50.0,85,0.0,32.0,38,250.0,85,32.0,5.0,50.0,50.0,Fail,C,0.0

In [16]:
values ={'Age':25,'Maths ':91,'Geography':99}
df.fillna(value=values)

,S No.,Student Name,Age,Hindi,English,Maths,Geography,History,Marks_Total,Maximum,Minimum,Count,AVG,%TAGE,Result,Grade,Result1
0,1,Paras,21.0,32.0,80,90.0,90.0,78,370.0,90,32.0,5.0,74.0,74.0,Fail,A,NaN
1,2,Mahendra,20.0,85.0,12,65.0,80.0,91,333.0,91,12.0,5.0,66.6,66.6,Fail,A,NaN
2,3,Simaran,NaN,91.0,65,23.0,99.0,45,294.0,91,23.0,NaN,58.8,58.8,Fail,B,NaN
3,4,Sonu,23.0,71.0,45,45.0,60.0,33,254.0,71,33.0,5.0,50.8,50.8,Pass,C,NaN
4,5,Dipak,19.0,NaN,32,85.0,50.0,48,NaN,85,32.0,5.0,60.0,60.0,NaN,B,NaN
5,6,Rana,18.0,73.0,30,39.0,40.0,7,189.0,73,7.0,5.0,37.8,37.8,Fail,D,NaN
6,7,Sonam,17.0,25.0,40,48.0,26.0,15,154.0,48,NaN,5.0,30.8,30.8,Fail,F,NaN
7,8,Shubham,20.0,81.0,78,76.0,56.0,65,356.0,81,56.0,5.0,71.2,71.2,Pass,A,NaN
8,9,Engla,24.0,88.0,32,1.0,48.0,35,204.0,88,1.0,5.0,40.8,40.8,Fail,C,NaN
9,10,Juhi,NaN,50.0,85,91.0,32.0,38,250.0,85,32.0,5.0,50.0,50.0,Fail,C,NaN