Dataframe

In [1]:
import pandas as pd

In [20]:
data = {
    'Name':["Sushil","Sanku","Himanshu","Nilesh","Sonu"],
    'Age':[20,22,19,23,17],
    'City':["Bhopal","Indore","Delhi","Balaghat",""],
    'Salary':[55000,45000,23000,75000,8000]
}

In [21]:
df = pd.DataFrame(data)
df

       Name  Age      City  Salary
0    Sushil   20    Bhopal   55000
1     Sanku   22    Indore   45000
2  Himanshu   19     Delhi   23000
3    Nilesh   23  Balaghat   75000
4      Sonu   17              8000

In [26]:
df[["Age","City"]]

   Age      City
0   20    Bhopal
1   22    Indore
2   19     Delhi
3   23  Balaghat
4   17

In [32]:
df["M.Number"] =[8349257120,7828795338,7697449908,7770803097,7509217463] # for Add Column
df

       Name  Age      City  Salary    M.Number
0    Sushil   20    Bhopal   55000  8349257120
1     Sanku   22    Indore   45000  7828795338
2  Himanshu   19     Delhi   23000  7697449908
3    Nilesh   23  Balaghat   75000  7770803097
4      Sonu   17              8000  7509217463

In [33]:
df.drop("M.Number",axis=1) # for Delete Column

       Name  Age      City  Salary
0    Sushil   20    Bhopal   55000
1     Sanku   22    Indore   45000
2  Himanshu   19     Delhi   23000
3    Nilesh   23  Balaghat   75000
4      Sonu   17              8000

In [35]:
df.loc[0]

Name            Sushil
Age                 20
City            Bhopal
Salary           55000
M.Number    8349257120
Name: 0, dtype: object

In [37]:
df.loc[[0,3]]

     Name  Age      City  Salary    M.Number
0  Sushil   20    Bhopal   55000  8349257120
3  Nilesh   23  Balaghat   75000  7770803097

In [39]:
df.iloc[4]

Name              Sonu
Age                 17
City
Salary            8000
M.Number    7509217463
Name: 4, dtype: object

Select Subset of Rows and Column

In [40]:
df

       Name  Age      City  Salary    M.Number
0    Sushil   20    Bhopal   55000  8349257120
1     Sanku   22    Indore   45000  7828795338
2  Himanshu   19     Delhi   23000  7697449908
3    Nilesh   23  Balaghat   75000  7770803097
4      Sonu   17              8000  7509217463

In [45]:
df.loc[[1,2]][["City","Salary"]]

     City  Salary
1  Indore   45000
2   Delhi   23000

In [46]:
df.loc[[2,3]][["Name",'Age']]

       Name  Age
2  Himanshu   19
3    Nilesh   23

Condionsl Selection

In [ ]:
df[df[("Age")]>20] #condition selection

     Name  Age      City  Salary    M.Number
1   Sanku   22    Indore   45000  7828795338
3  Nilesh   23  Balaghat   75000  7770803097

In [52]:
df[(df["Salary"]>50000) & (df["City"]=="Balaghat")]

     Name  Age      City  Salary    M.Number
3  Nilesh   23  Balaghat   75000  7770803097