In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("anime.csv")
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [3]:
def extract_episodes(txt):
    check = False
    Data = ""
    for i in txt:
        if i==")":
          check = False
          return  Data
        if check ==True:
           Data=Data + i
        if i =="(":
           check = True

In [4]:
df["Episodes"] = df['Title'].apply(extract_episodes)
df["Episodes"] = df["Episodes"].str.replace(" eps","")
df.head()

   Rank                                              Title  Score Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10       64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07       24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06       13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06       51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05       10

In [5]:
df["Episodes"].dtype

In [6]:
df["Episodes"] = df["Episodes"].astype(int)
df.head()

   Rank                                              Title  Score  Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10        64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07        24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06        13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06        51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05        10

Q2. Make a new column for time stamp

In [7]:
df.loc[2]["Title"]

'Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members'

In [8]:
def time_Stamp(txt1):
    check = False
    data = ""
    for i in txt1:
        if i==",":
            check = False
            return data
        if check ==True:
            data = data+i
        if i == ")":
           check = True

In [9]:
df["Time_Stamp"]  = df["Title"].apply(time_Stamp)
df.head()

,Rank,Title,Score,Episodes,Time_Stamp
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 20103
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 20112
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022474
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016605
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 20192

In [10]:
def time_Stamp1(txt):
    check = False
    data = ""
    for i in range(len(txt)):
        if txt[i] == ")":
            for j in range(i+1,i+20):
                data +=txt[j]
            return data

In [11]:
df["Time_Stamp"]  = df["Title"].apply(time_Stamp1)
df.head()

,Rank,Title,Score,Episodes,Time_Stamp
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [12]:

def calculate_date_diff(df, col_name):
    dates = df[col_name].str.split(' - ', expand=True)
    
    start = pd.to_datetime(dates[0], format='%b %Y')
    end = pd.to_datetime(dates[1], format='%b %Y')
    
    df['diff_days'] = (end - start).dt.days
    df['diff_months'] = (end.dt.year - start.dt.year) * 12 + (end.dt.month - start.dt.month)
    
    return df

In [13]:


df1 = calculate_date_diff(df, 'Time_Stamp')
df1.head()

,Rank,Title,Score,Episodes,Time_Stamp,diff_days,diff_months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,456,15
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,153,5
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,61,2
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,335,11
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,91,3

In [14]:
df.drop("diff_years",axis=1,inplace=True)

KeyError: "['diff_years'] not found in axis"

In [ ]:
df.head()

,Rank,Title,Score,Episodes,Time_Stamp,diff_days,diff_months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,456,15
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,153,5
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,61,2
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,335,11
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,91,3

Which anime is Highest Score

In [15]:
df[df["Score"] == df['Score'].max()]["Title"]

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
Name: Title, dtype: str

In [16]:
df[df["Episodes"]==df["Episodes"].max()]["Title"] #Which anime has the highest episode count

15    GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...
Name: Title, dtype: str

In [17]:
df[df["diff_days"] == df["diff_days"].max()] # Which is the longest running anime

,Rank,Title,Score,Episodes,Time_Stamp,diff_days,diff_months
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,3347,110

In [18]:
df["Episodes"].value_counts().head(5)

Episodes
1     9
13    6
12    6
24    4
26    4
Name: count, dtype: int64